const config = require('./utils/config')
const blogsRouter = require('./controllers/blogs')
const express = require('express')
const mongoose = require('mongoose')
const cors = require('cors')
const bodyParser = require('body-parser')
const app = express()